# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HxUXYUtFs6RXcAJHY45sT4g7sK7913Pb
"""

# Install necessary packages
import subprocess
import sys

# Install packages if not already installed
def install_packages():
    try:
        import nltk
        import streamlit
    except ImportError:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "nltk", "streamlit"])
        import nltk
        import streamlit

# Call the function to install required packages
install_packages()

# Now you can proceed with your existing imports and code
import random
from nltk.sentiment import SentimentIntensityAnalyzer
import nltk
import streamlit as st

# Ensure the necessary nltk data is downloaded
nltk.download('vader_lexicon')

# Define the MentorBot class as before
# Your chatbot code here...


# Create a requirements.txt file for deployment
with open('requirements.txt', 'w') as f:
    f.write("nltk\n")
    f.write("streamlit\n")

import random
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
import streamlit as st

# Ensure the necessary nltk data is downloaded
nltk.download('vader_lexicon')

# Define the MentorBot class
class MentorBot:
    def __init__(self):
        self.user_info = {}
        self.sia = SentimentIntensityAnalyzer()

    def greet(self):
        greetings = [
            "Hello! I'm here to support you on your journey.",
            "Hey there! How can I help you today?",
            "Hi! I'm here to listen and assist you."
        ]
        return random.choice(greetings)

    def get_user_name(self):
        if 'name' not in self.user_info:
            self.user_info['name'] = st.text_input("What should I call you?")
        return f"Nice to meet you, {self.user_info['name']}!" if self.user_info['name'] else ""

    def respond_to_emotion(self, text):
        sentiment_score = self.sia.polarity_scores(text)['compound']
        if sentiment_score >= 0.5:
            response = "I'm glad you're feeling positive! Let me know how I can assist you further."
        elif sentiment_score <= -0.5:
            response = "It sounds like things might be challenging. I'm here to support you however you need."
        else:
            response = "Thanks for sharing. I'm here to provide any support or advice you need."
        return response

    def deliver_feedback(self, feedback, delivery_preference="constructive"):
        feedback_responses = {
            "constructive": f"I have some constructive feedback for you: {feedback}. Remember, feedback is here to help you grow.",
            "supportive": f"Here’s something I think could help you shine even more: {feedback}. You’re already doing so well!",
            "humor": f"So, funny story—{feedback}. Keep up the great work, you're making strides!"
        }
        return feedback_responses.get(delivery_preference, "constructive")

    def mentor_session(self):
        st.write(self.greet())

        # Input for user name
        name_response = self.get_user_name()
        if name_response:
            st.write(name_response)

        # Conversation input
        user_input = st.text_input("Tell me what’s on your mind, or type 'exit' to end the session:")

        if user_input:
            # Respond based on sentiment
            st.write(self.respond_to_emotion(user_input))

            # Ask if user wants feedback delivery in a specific style
            feedback = "Your recent work shows great potential, but you might want to focus on improving X."
            st.write("How would you like feedback delivered? Options: 'constructive', 'supportive', 'humor'")
            feedback_style = st.selectbox("Choose a style:", ["constructive", "supportive", "humor"])
            st.write(self.deliver_feedback(feedback, feedback_style))

# Instantiate the bot and start the mentor session
if 'mentor_bot' not in st.session_state:
    st.session_state.mentor_bot = MentorBot()

st.session_state.mentor_bot.mentor_session()